// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

// GetHealthStatusResponseBody - Health status
type GetHealthStatusResponseBody struct {
	Status *string `json:"status,omitzero"`
}

func (g *GetHealthStatusResponseBody) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetHealthStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Health status
	Object *GetHealthStatusResponseBody
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (g GetHealthStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetHealthStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetHealthStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetHealthStatusResponse) GetObject() *GetHealthStatusResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetHealthStatusResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if g == nil {
		return nil
	}
	return g.DefaultErrorDTO
}
