// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1APICredentialsDeleteAPICredentialRequest struct {
	// The <code>id</code> of the Organization whose API Credential you want to delete.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// The <code>clientId</code> of the API Credential to delete.
	APICredentialID string `pathParam:"style=simple,explode=false,name=apiCredentialId"`
}

func (v *V1APICredentialsDeleteAPICredentialRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1APICredentialsDeleteAPICredentialRequest) GetAPICredentialID() string {
	if v == nil {
		return ""
	}
	return v.APICredentialID
}

type V1APICredentialsDeleteAPICredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1APICredentialsDeleteAPICredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1APICredentialsDeleteAPICredentialResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
