// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1APICredentialsGetAPICredentialRequest struct {
	// The <code>id</code> of the Organization whose API Credential you want to retrieve.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// The <code>clientId</code> of the API Credential to retrieve.
	APICredentialID string `pathParam:"style=simple,explode=false,name=apiCredentialId"`
}

func (v *V1APICredentialsGetAPICredentialRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1APICredentialsGetAPICredentialRequest) GetAPICredentialID() string {
	if v == nil {
		return ""
	}
	return v.APICredentialID
}

type V1APICredentialsGetAPICredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// API Credential retrieved
	APICredentialResponseSchema *components.APICredentialResponseSchema
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1APICredentialsGetAPICredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1APICredentialsGetAPICredentialResponse) GetAPICredentialResponseSchema() *components.APICredentialResponseSchema {
	if v == nil {
		return nil
	}
	return v.APICredentialResponseSchema
}

func (v *V1APICredentialsGetAPICredentialResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
