// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1APICredentialsUpdateAPICredentialRequest struct {
	// The <code>id</code> of the Organization whose API Credential you want to update.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// The <code>clientId</code> of the API Credential to update.
	APICredentialID               string                                   `pathParam:"style=simple,explode=false,name=apiCredentialId"`
	APICredentialUpdateRequestDTO components.APICredentialUpdateRequestDTO `request:"mediaType=application/json"`
}

func (v *V1APICredentialsUpdateAPICredentialRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1APICredentialsUpdateAPICredentialRequest) GetAPICredentialID() string {
	if v == nil {
		return ""
	}
	return v.APICredentialID
}

func (v *V1APICredentialsUpdateAPICredentialRequest) GetAPICredentialUpdateRequestDTO() components.APICredentialUpdateRequestDTO {
	if v == nil {
		return components.APICredentialUpdateRequestDTO{}
	}
	return v.APICredentialUpdateRequestDTO
}

type V1APICredentialsUpdateAPICredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1APICredentialsUpdateAPICredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1APICredentialsUpdateAPICredentialResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
