// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1APICredentialsCreateAPICredentialRequest struct {
	// The <code>id</code> of the Organization where you want to create the API Credential.
	OrganizationID                string                                   `pathParam:"style=simple,explode=false,name=organizationId"`
	APICredentialCreateRequestDTO components.APICredentialCreateRequestDTO `request:"mediaType=application/json"`
}

func (v *V1APICredentialsCreateAPICredentialRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1APICredentialsCreateAPICredentialRequest) GetAPICredentialCreateRequestDTO() components.APICredentialCreateRequestDTO {
	if v == nil {
		return components.APICredentialCreateRequestDTO{}
	}
	return v.APICredentialCreateRequestDTO
}

type V1APICredentialsCreateAPICredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// API Credential created
	APICredentialResponseSchema *components.APICredentialResponseSchema
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1APICredentialsCreateAPICredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1APICredentialsCreateAPICredentialResponse) GetAPICredentialResponseSchema() *components.APICredentialResponseSchema {
	if v == nil {
		return nil
	}
	return v.APICredentialResponseSchema
}

func (v *V1APICredentialsCreateAPICredentialResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
