// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1APICredentialsListAPICredentialsRequest struct {
	// The <code>id</code> of the Organization that owns the API credentials.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (v *V1APICredentialsListAPICredentialsRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

type V1APICredentialsListAPICredentialsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The API credentials have been retrieved
	APICredentialsListResponseDTO *components.APICredentialsListResponseDTO
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1APICredentialsListAPICredentialsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1APICredentialsListAPICredentialsResponse) GetAPICredentialsListResponseDTO() *components.APICredentialsListResponseDTO {
	if v == nil {
		return nil
	}
	return v.APICredentialsListResponseDTO
}

func (v *V1APICredentialsListAPICredentialsResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
