// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
	"time"
)

type V1BillingGetCreditsTimeseriesRequest struct {
	// The <code>id</code> of the Organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Inclusive start of the query date range in ISO 8601 format.
	StartingOn time.Time `queryParam:"style=form,explode=true,name=startingOn"`
	// Exclusive end of the query date range in ISO 8601 format.
	EndingBefore time.Time `queryParam:"style=form,explode=true,name=endingBefore"`
	// Aggregation granularity for timeseries data.
	Window components.BillingWindow `queryParam:"style=form,explode=true,name=window"`
}

func (v V1BillingGetCreditsTimeseriesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetCreditsTimeseriesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetCreditsTimeseriesRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1BillingGetCreditsTimeseriesRequest) GetStartingOn() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartingOn
}

func (v *V1BillingGetCreditsTimeseriesRequest) GetEndingBefore() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndingBefore
}

func (v *V1BillingGetCreditsTimeseriesRequest) GetWindow() components.BillingWindow {
	if v == nil {
		return components.BillingWindow("")
	}
	return v.Window
}

// #region class-body-v1billinggetcreditstimeseriesrequest
// #endregion class-body-v1billinggetcreditstimeseriesrequest

type V1BillingGetCreditsTimeseriesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Credits timeseries data.
	CreditsTimeseriesResponseDTO *components.CreditsTimeseriesResponseDTO
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v V1BillingGetCreditsTimeseriesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetCreditsTimeseriesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetCreditsTimeseriesResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1BillingGetCreditsTimeseriesResponse) GetCreditsTimeseriesResponseDTO() *components.CreditsTimeseriesResponseDTO {
	if v == nil {
		return nil
	}
	return v.CreditsTimeseriesResponseDTO
}

func (v *V1BillingGetCreditsTimeseriesResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}

// #region class-body-v1billinggetcreditstimeseriesresponse
// #endregion class-body-v1billinggetcreditstimeseriesresponse
