// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
	"time"
)

type V1BillingGetContractsUtilizationRequest struct {
	// The <code>id</code> of the Organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Inclusive start of the query date range in ISO 8601 format.
	StartingOn time.Time `queryParam:"style=form,explode=true,name=startingOn"`
	// Exclusive end of the query date range in ISO 8601 format.
	EndingBefore time.Time `queryParam:"style=form,explode=true,name=endingBefore"`
	// Aggregation granularity for credit utilization data.
	Window components.BillingWindow `queryParam:"style=form,explode=true,name=window"`
}

func (v V1BillingGetContractsUtilizationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetContractsUtilizationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetContractsUtilizationRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1BillingGetContractsUtilizationRequest) GetStartingOn() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartingOn
}

func (v *V1BillingGetContractsUtilizationRequest) GetEndingBefore() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndingBefore
}

func (v *V1BillingGetContractsUtilizationRequest) GetWindow() components.BillingWindow {
	if v == nil {
		return components.BillingWindow("")
	}
	return v.Window
}

// #region class-body-v1billinggetcontractsutilizationrequest
// #endregion class-body-v1billinggetcontractsutilizationrequest

type V1BillingGetContractsUtilizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Contract credit utilization data.
	ContractsUtilizationResponseDTO *components.ContractsUtilizationResponseDTO
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v V1BillingGetContractsUtilizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetContractsUtilizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetContractsUtilizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1BillingGetContractsUtilizationResponse) GetContractsUtilizationResponseDTO() *components.ContractsUtilizationResponseDTO {
	if v == nil {
		return nil
	}
	return v.ContractsUtilizationResponseDTO
}

func (v *V1BillingGetContractsUtilizationResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}

// #region class-body-v1billinggetcontractsutilizationresponse
// #endregion class-body-v1billinggetcontractsutilizationresponse
