// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
	"time"
)

type V1BillingGetCreditsGrantsRequest struct {
	// The <code>id</code> of the Organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Inclusive start of the query date range in ISO 8601 format.
	StartingOn time.Time `queryParam:"style=form,explode=true,name=startingOn"`
	// Exclusive end of the query date range in ISO 8601 format.
	EndingBefore time.Time `queryParam:"style=form,explode=true,name=endingBefore"`
	// Aggregation granularity for credit grant data.
	Window components.BillingWindow `queryParam:"style=form,explode=true,name=window"`
}

func (v V1BillingGetCreditsGrantsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetCreditsGrantsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetCreditsGrantsRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1BillingGetCreditsGrantsRequest) GetStartingOn() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartingOn
}

func (v *V1BillingGetCreditsGrantsRequest) GetEndingBefore() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndingBefore
}

func (v *V1BillingGetCreditsGrantsRequest) GetWindow() components.BillingWindow {
	if v == nil {
		return components.BillingWindow("")
	}
	return v.Window
}

// #region class-body-v1billinggetcreditsgrantsrequest
// #endregion class-body-v1billinggetcreditsgrantsrequest

type V1BillingGetCreditsGrantsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Credit grants for the queried period.
	CreditGrantsResponseDTO *components.CreditGrantsResponseDTO
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v V1BillingGetCreditsGrantsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetCreditsGrantsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetCreditsGrantsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1BillingGetCreditsGrantsResponse) GetCreditGrantsResponseDTO() *components.CreditGrantsResponseDTO {
	if v == nil {
		return nil
	}
	return v.CreditGrantsResponseDTO
}

func (v *V1BillingGetCreditsGrantsResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}

// #region class-body-v1billinggetcreditsgrantsresponse
// #endregion class-body-v1billinggetcreditsgrantsresponse
