// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
	"time"
)

type V1BillingGetCreditsStatsRequest struct {
	// The <code>id</code> of the Organization.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Inclusive start of the query date range in ISO 8601 format.
	StartingOn time.Time `queryParam:"style=form,explode=true,name=startingOn"`
	// Exclusive end of the query date range in ISO 8601 format.
	EndingBefore time.Time `queryParam:"style=form,explode=true,name=endingBefore"`
	// Aggregation granularity for credit balance and consumption.
	Window components.BillingWindow `queryParam:"style=form,explode=true,name=window"`
}

func (v V1BillingGetCreditsStatsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetCreditsStatsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetCreditsStatsRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1BillingGetCreditsStatsRequest) GetStartingOn() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.StartingOn
}

func (v *V1BillingGetCreditsStatsRequest) GetEndingBefore() time.Time {
	if v == nil {
		return time.Time{}
	}
	return v.EndingBefore
}

func (v *V1BillingGetCreditsStatsRequest) GetWindow() components.BillingWindow {
	if v == nil {
		return components.BillingWindow("")
	}
	return v.Window
}

// #region class-body-v1billinggetcreditsstatsrequest
// #endregion class-body-v1billinggetcreditsstatsrequest

type V1BillingGetCreditsStatsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Credit balance and consumption totals.
	CreditsStatsResponseDTO *components.CreditsStatsResponseDTO
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v V1BillingGetCreditsStatsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1BillingGetCreditsStatsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1BillingGetCreditsStatsResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1BillingGetCreditsStatsResponse) GetCreditsStatsResponseDTO() *components.CreditsStatsResponseDTO {
	if v == nil {
		return nil
	}
	return v.CreditsStatsResponseDTO
}

func (v *V1BillingGetCreditsStatsResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}

// #region class-body-v1billinggetcreditsstatsresponse
// #endregion class-body-v1billinggetcreditsstatsresponse
