// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesGetWorkspaceRequest struct {
	// The <code>id</code> of the Organization that contains the Workspace.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// The <code>id</code> of the Workspace to get.
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceId"`
}

func (v *V1WorkspacesGetWorkspaceRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1WorkspacesGetWorkspaceRequest) GetWorkspaceID() string {
	if v == nil {
		return ""
	}
	return v.WorkspaceID
}

type V1WorkspacesGetWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Workspace details have been retrieved
	WorkspaceSchema *components.WorkspaceSchema
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1WorkspacesGetWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1WorkspacesGetWorkspaceResponse) GetWorkspaceSchema() *components.WorkspaceSchema {
	if v == nil {
		return nil
	}
	return v.WorkspaceSchema
}

func (v *V1WorkspacesGetWorkspaceResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
