// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesDeleteWorkspaceRequest struct {
	// The <code>id</code> of the Organization that contains the Workspace.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// The <code>id</code> of the Workspace to delete.
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceId"`
}

func (v *V1WorkspacesDeleteWorkspaceRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1WorkspacesDeleteWorkspaceRequest) GetWorkspaceID() string {
	if v == nil {
		return ""
	}
	return v.WorkspaceID
}

type V1WorkspacesDeleteWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1WorkspacesDeleteWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1WorkspacesDeleteWorkspaceResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
