// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesListWorkspacesSecurity struct {
	Oauth2 *components.SchemeOauth2 `security:"scheme,type=oauth2,subtype=client_credentials"`
	Bearer *string                  `security:"scheme,type=http,subtype=bearer,name=Authorization,env=criblmgmtplane_bearer"`
}

func (o *V1WorkspacesListWorkspacesSecurity) GetOauth2() *components.SchemeOauth2 {
	if o == nil {
		return nil
	}
	return o.Oauth2
}

func (o *V1WorkspacesListWorkspacesSecurity) GetBearer() *string {
	if o == nil {
		return nil
	}
	return o.Bearer
}

type V1WorkspacesListWorkspacesRequest struct {
	// Organization identifier
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (o *V1WorkspacesListWorkspacesRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

type V1WorkspacesListWorkspacesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of workspaces has been successfully retrieved
	WorkspacesListResponseDTO *components.WorkspacesListResponseDTO
}

func (o *V1WorkspacesListWorkspacesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V1WorkspacesListWorkspacesResponse) GetWorkspacesListResponseDTO() *components.WorkspacesListResponseDTO {
	if o == nil {
		return nil
	}
	return o.WorkspacesListResponseDTO
}
