// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesGetWorkspaceRequest struct {
	// Organization identifier
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Workspace identifier
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceId"`
}

func (v *V1WorkspacesGetWorkspaceRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1WorkspacesGetWorkspaceRequest) GetWorkspaceID() string {
	if v == nil {
		return ""
	}
	return v.WorkspaceID
}

type V1WorkspacesGetWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The workspace details have been successfully retrieved
	WorkspaceSchema *components.WorkspaceSchema
}

func (v *V1WorkspacesGetWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1WorkspacesGetWorkspaceResponse) GetWorkspaceSchema() *components.WorkspaceSchema {
	if v == nil {
		return nil
	}
	return v.WorkspaceSchema
}
