// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesListWorkspacesRequest struct {
	// The <code>id</code> of the Organization that contains the Workspaces.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (v *V1WorkspacesListWorkspacesRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

// #region class-body-v1workspaceslistworkspacesrequest
// #endregion class-body-v1workspaceslistworkspacesrequest

type V1WorkspacesListWorkspacesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of Workspaces has been successfully retrieved
	WorkspacesListResponseDTO *components.WorkspacesListResponseDTO
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v V1WorkspacesListWorkspacesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1WorkspacesListWorkspacesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1WorkspacesListWorkspacesResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1WorkspacesListWorkspacesResponse) GetWorkspacesListResponseDTO() *components.WorkspacesListResponseDTO {
	if v == nil {
		return nil
	}
	return v.WorkspacesListResponseDTO
}

func (v *V1WorkspacesListWorkspacesResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}

// #region class-body-v1workspaceslistworkspacesresponse
// #endregion class-body-v1workspaceslistworkspacesresponse
