// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesUpdateWorkspaceRequest struct {
	// The <code>id</code> of the Organization that contains the Workspace.
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// The <code>id</code> of the Workspace to update.
	WorkspaceID              string                              `pathParam:"style=simple,explode=false,name=workspaceId"`
	WorkspacePatchRequestDTO components.WorkspacePatchRequestDTO `request:"mediaType=application/json"`
}

func (v *V1WorkspacesUpdateWorkspaceRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1WorkspacesUpdateWorkspaceRequest) GetWorkspaceID() string {
	if v == nil {
		return ""
	}
	return v.WorkspaceID
}

func (v *V1WorkspacesUpdateWorkspaceRequest) GetWorkspacePatchRequestDTO() components.WorkspacePatchRequestDTO {
	if v == nil {
		return components.WorkspacePatchRequestDTO{}
	}
	return v.WorkspacePatchRequestDTO
}

type V1WorkspacesUpdateWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Workspace has been successfully updated
	WorkspaceSchema *components.WorkspaceSchema
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v *V1WorkspacesUpdateWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1WorkspacesUpdateWorkspaceResponse) GetWorkspaceSchema() *components.WorkspaceSchema {
	if v == nil {
		return nil
	}
	return v.WorkspaceSchema
}

func (v *V1WorkspacesUpdateWorkspaceResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}
