// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesCreateWorkspaceRequest struct {
	// The <code>id</code> of the Organization where you want to create the Workspace.
	OrganizationID            string                               `pathParam:"style=simple,explode=false,name=organizationId"`
	WorkspaceCreateRequestDTO components.WorkspaceCreateRequestDTO `request:"mediaType=application/json"`
}

func (v *V1WorkspacesCreateWorkspaceRequest) GetOrganizationID() string {
	if v == nil {
		return ""
	}
	return v.OrganizationID
}

func (v *V1WorkspacesCreateWorkspaceRequest) GetWorkspaceCreateRequestDTO() components.WorkspaceCreateRequestDTO {
	if v == nil {
		return components.WorkspaceCreateRequestDTO{}
	}
	return v.WorkspaceCreateRequestDTO
}

// #region class-body-v1workspacescreateworkspacerequest
// #endregion class-body-v1workspacescreateworkspacerequest

type V1WorkspacesCreateWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Workspace has been successfully created
	WorkspaceSchema *components.WorkspaceSchema
	// Default error response
	DefaultErrorDTO *components.DefaultErrorDTO
}

func (v V1WorkspacesCreateWorkspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1WorkspacesCreateWorkspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V1WorkspacesCreateWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V1WorkspacesCreateWorkspaceResponse) GetWorkspaceSchema() *components.WorkspaceSchema {
	if v == nil {
		return nil
	}
	return v.WorkspaceSchema
}

func (v *V1WorkspacesCreateWorkspaceResponse) GetDefaultErrorDTO() *components.DefaultErrorDTO {
	if v == nil {
		return nil
	}
	return v.DefaultErrorDTO
}

// #region class-body-v1workspacescreateworkspaceresponse
// #endregion class-body-v1workspacescreateworkspaceresponse
