// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesUpdateWorkspaceRequest struct {
	// Organization identifier
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Workspace identifier
	WorkspaceID              string                              `pathParam:"style=simple,explode=false,name=workspaceId"`
	WorkspacePatchRequestDTO components.WorkspacePatchRequestDTO `request:"mediaType=application/json"`
}

func (o *V1WorkspacesUpdateWorkspaceRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *V1WorkspacesUpdateWorkspaceRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *V1WorkspacesUpdateWorkspaceRequest) GetWorkspacePatchRequestDTO() components.WorkspacePatchRequestDTO {
	if o == nil {
		return components.WorkspacePatchRequestDTO{}
	}
	return o.WorkspacePatchRequestDTO
}

type V1WorkspacesUpdateWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The workspace has been successfully updated
	WorkspaceSchema *components.WorkspaceSchema
}

func (o *V1WorkspacesUpdateWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V1WorkspacesUpdateWorkspaceResponse) GetWorkspaceSchema() *components.WorkspaceSchema {
	if o == nil {
		return nil
	}
	return o.WorkspaceSchema
}
