// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesCreateWorkspaceSecurity struct {
	Oauth2 *components.SchemeOauth2 `security:"scheme,type=oauth2,subtype=client_credentials"`
	Bearer *string                  `security:"scheme,type=http,subtype=bearer,name=Authorization,env=criblmgmtplane_bearer"`
}

func (o *V1WorkspacesCreateWorkspaceSecurity) GetOauth2() *components.SchemeOauth2 {
	if o == nil {
		return nil
	}
	return o.Oauth2
}

func (o *V1WorkspacesCreateWorkspaceSecurity) GetBearer() *string {
	if o == nil {
		return nil
	}
	return o.Bearer
}

type V1WorkspacesCreateWorkspaceRequest struct {
	// Organization identifier
	OrganizationID            string                               `pathParam:"style=simple,explode=false,name=organizationId"`
	WorkspaceCreateRequestDTO components.WorkspaceCreateRequestDTO `request:"mediaType=application/json"`
}

func (o *V1WorkspacesCreateWorkspaceRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *V1WorkspacesCreateWorkspaceRequest) GetWorkspaceCreateRequestDTO() components.WorkspaceCreateRequestDTO {
	if o == nil {
		return components.WorkspaceCreateRequestDTO{}
	}
	return o.WorkspaceCreateRequestDTO
}

type V1WorkspacesCreateWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The workspace has been successfully created
	WorkspaceSchema *components.WorkspaceSchema
}

func (o *V1WorkspacesCreateWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V1WorkspacesCreateWorkspaceResponse) GetWorkspaceSchema() *components.WorkspaceSchema {
	if o == nil {
		return nil
	}
	return o.WorkspaceSchema
}
