// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type V1WorkspacesDeleteWorkspaceSecurity struct {
	Oauth2 *components.SchemeOauth2 `security:"scheme,type=oauth2,subtype=client_credentials"`
	Bearer *string                  `security:"scheme,type=http,subtype=bearer,name=Authorization,env=criblmgmtplane_bearer"`
}

func (o *V1WorkspacesDeleteWorkspaceSecurity) GetOauth2() *components.SchemeOauth2 {
	if o == nil {
		return nil
	}
	return o.Oauth2
}

func (o *V1WorkspacesDeleteWorkspaceSecurity) GetBearer() *string {
	if o == nil {
		return nil
	}
	return o.Bearer
}

type V1WorkspacesDeleteWorkspaceRequest struct {
	// Organization identifier
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Workspace identifier
	WorkspaceID string `pathParam:"style=simple,explode=false,name=workspaceId"`
}

func (o *V1WorkspacesDeleteWorkspaceRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *V1WorkspacesDeleteWorkspaceRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type V1WorkspacesDeleteWorkspaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *V1WorkspacesDeleteWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
