// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	criblcloudmanagementsdkgo "github.com/criblio/cribl-cloud-management-sdk-go"
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestCriblmgmtplane_DummyServiceStatus(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("dummyServiceStatus")

	s := criblcloudmanagementsdkgo.New(
		utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080"),
		criblcloudmanagementsdkgo.WithClient(testHTTPClient),
		criblcloudmanagementsdkgo.WithSecurity(utils.GetEnv("CRIBLMGMTPLANE_BEARER_AUTH", "value")),
	)

	res, err := s.DummyServiceStatus(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}
