// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialListItemSchema struct {
	// Human-readable name of the API Credential.
	Name string `json:"name"`
	// Brief description of the purpose and usage for the API Credential.
	Description string `json:"description"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled bool `json:"enabled"`
	// Unique ID of the Workspace.
	WorkspaceID string `json:"workspaceId"`
	// Unique ID of the Organization.
	OrganizationID string `json:"organizationId"`
	// Client ID for the API Credential.
	ClientID string `json:"clientId"`
	// Role assignments for the API Credential.
	Roles APICredentialRolesSchema `json:"roles"`
	// Member who created the API Credential.
	CreatedBy string `json:"createdBy"`
	// ISO 8601 timestamp when the API Credential was created.
	CreatedDate string `json:"createdDate"`
	// Member who last updated the API Credential.
	LastUpdatedBy string `json:"lastUpdatedBy"`
	// ISO 8601 timestamp when the API Credential was last updated.
	LastUpdatedDate string `json:"lastUpdatedDate"`
}

func (a *APICredentialListItemSchema) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APICredentialListItemSchema) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APICredentialListItemSchema) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *APICredentialListItemSchema) GetWorkspaceID() string {
	if a == nil {
		return ""
	}
	return a.WorkspaceID
}

func (a *APICredentialListItemSchema) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *APICredentialListItemSchema) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *APICredentialListItemSchema) GetRoles() APICredentialRolesSchema {
	if a == nil {
		return APICredentialRolesSchema{}
	}
	return a.Roles
}

func (a *APICredentialListItemSchema) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *APICredentialListItemSchema) GetCreatedDate() string {
	if a == nil {
		return ""
	}
	return a.CreatedDate
}

func (a *APICredentialListItemSchema) GetLastUpdatedBy() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedBy
}

func (a *APICredentialListItemSchema) GetLastUpdatedDate() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedDate
}
