// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialResponseSchema struct {
	// Human-readable name of the API Credential.
	Name string `json:"name"`
	// Brief description of the purpose and usage for the API Credential.
	Description string `json:"description"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled bool `json:"enabled"`
	// Unique ID of the Workspace.
	WorkspaceID string `json:"workspaceId"`
	// Unique ID of the Organization.
	OrganizationID string `json:"organizationId"`
	// Client ID for the API Credential.
	ClientID string `json:"clientId"`
	// Role assignments for the API Credential.
	Roles APICredentialRolesSchema `json:"roles"`
	// Member who created the API Credential.
	CreatedBy string `json:"createdBy"`
	// ISO 8601 timestamp when the API Credential was created.
	CreatedDate string `json:"createdDate"`
	// Member who last updated the API Credential.
	LastUpdatedBy string `json:"lastUpdatedBy"`
	// ISO 8601 timestamp when the API Credential was last updated.
	LastUpdatedDate string `json:"lastUpdatedDate"`
	// Client Secret for the API Credential. The Client Secret is sensitive information and should be kept private. Only <code>POST</code> responses include the Client Secret. For other methods, responses return an empty string.
	ClientSecret string `json:"clientSecret"`
}

func (a *APICredentialResponseSchema) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APICredentialResponseSchema) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APICredentialResponseSchema) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *APICredentialResponseSchema) GetWorkspaceID() string {
	if a == nil {
		return ""
	}
	return a.WorkspaceID
}

func (a *APICredentialResponseSchema) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *APICredentialResponseSchema) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *APICredentialResponseSchema) GetRoles() APICredentialRolesSchema {
	if a == nil {
		return APICredentialRolesSchema{}
	}
	return a.Roles
}

func (a *APICredentialResponseSchema) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *APICredentialResponseSchema) GetCreatedDate() string {
	if a == nil {
		return ""
	}
	return a.CreatedDate
}

func (a *APICredentialResponseSchema) GetLastUpdatedBy() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedBy
}

func (a *APICredentialResponseSchema) GetLastUpdatedDate() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedDate
}

func (a *APICredentialResponseSchema) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}
