// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OrganizationRole - Organization-level Role assigned to the API Credential.
type OrganizationRole string

const (
	OrganizationRoleOwner OrganizationRole = "owner"
	OrganizationRoleAdmin OrganizationRole = "admin"
	OrganizationRoleUser  OrganizationRole = "user"
)

func (e OrganizationRole) ToPointer() *OrganizationRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OrganizationRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "owner", "admin", "user":
			return true
		}
	}
	return false
}

type APICredentialRolesSchema struct {
	// Organization-level Role assigned to the API Credential.
	OrganizationRole OrganizationRole `json:"organizationRole"`
	// Workspace-level Roles assigned to the API Credential.
	Workspaces []WorkspaceRoleSchema `json:"workspaces,omitempty"`
}

func (a *APICredentialRolesSchema) GetOrganizationRole() OrganizationRole {
	if a == nil {
		return OrganizationRole("")
	}
	return a.OrganizationRole
}

func (a *APICredentialRolesSchema) GetWorkspaces() []WorkspaceRoleSchema {
	if a == nil {
		return nil
	}
	return a.Workspaces
}
