// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialSchema struct {
	// Human friendly name of the credential
	Name string `json:"name"`
	// Description of how or where the credential is used
	Description string `json:"description"`
	// Whether the credential is enabled
	Enabled bool `json:"enabled"`
	// Workspace identifier
	WorkspaceID string `json:"workspaceId"`
	// Organization identifier
	OrganizationID string `json:"organizationId"`
	// Client identifier
	ClientID string `json:"clientId"`
	// Client secret
	ClientSecret string `json:"clientSecret"`
	// Role assignments for this credential
	Roles APICredentialRolesSchema `json:"roles"`
	// User who created the credential
	CreatedBy string `json:"createdBy"`
	// ISO-8601 timestamp when the credential was created
	CreatedDate string `json:"createdDate"`
	// User who last updated the credential
	LastUpdatedBy string `json:"lastUpdatedBy"`
	// ISO-8601 timestamp when the credential was last updated
	LastUpdatedDate string `json:"lastUpdatedDate"`
}

func (a *APICredentialSchema) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APICredentialSchema) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APICredentialSchema) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *APICredentialSchema) GetWorkspaceID() string {
	if a == nil {
		return ""
	}
	return a.WorkspaceID
}

func (a *APICredentialSchema) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *APICredentialSchema) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *APICredentialSchema) GetClientSecret() string {
	if a == nil {
		return ""
	}
	return a.ClientSecret
}

func (a *APICredentialSchema) GetRoles() APICredentialRolesSchema {
	if a == nil {
		return APICredentialRolesSchema{}
	}
	return a.Roles
}

func (a *APICredentialSchema) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *APICredentialSchema) GetCreatedDate() string {
	if a == nil {
		return ""
	}
	return a.CreatedDate
}

func (a *APICredentialSchema) GetLastUpdatedBy() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedBy
}

func (a *APICredentialSchema) GetLastUpdatedDate() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedDate
}
