// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"time"
)

type APICredentialResponseSchema struct {
	// Human-readable name of the API Credential.
	Name string `json:"name"`
	// Brief description of the purpose and usage for the API Credential.
	Description string `json:"description"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled bool `json:"enabled"`
	// Unique ID of the Organization.
	OrganizationID string `json:"organizationId"`
	// Client ID for the API Credential.
	ClientID string `json:"clientId"`
	// Role assignments for the API Credential.
	Roles APICredentialRolesSchema `json:"roles"`
	// CIDR range enforced as the IP allowlist for the API Credential. An empty array means that the API Credential has no IP restrictions.
	IPAllowlist []string `json:"ipAllowlist"`
	// Member who created the API Credential.
	CreatedBy string `json:"createdBy"`
	// ISO 8601 timestamp when the API Credential was created.
	CreatedDate time.Time `json:"createdDate"`
	// Member who last updated the API Credential.
	LastUpdatedBy string `json:"lastUpdatedBy"`
	// ISO 8601 timestamp when the API Credential was last updated.
	LastUpdatedDate time.Time `json:"lastUpdatedDate"`
}

func (a APICredentialResponseSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APICredentialResponseSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APICredentialResponseSchema) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APICredentialResponseSchema) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APICredentialResponseSchema) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *APICredentialResponseSchema) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *APICredentialResponseSchema) GetClientID() string {
	if a == nil {
		return ""
	}
	return a.ClientID
}

func (a *APICredentialResponseSchema) GetRoles() APICredentialRolesSchema {
	if a == nil {
		return APICredentialRolesSchema{}
	}
	return a.Roles
}

func (a *APICredentialResponseSchema) GetIPAllowlist() []string {
	if a == nil {
		return []string{}
	}
	return a.IPAllowlist
}

func (a *APICredentialResponseSchema) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *APICredentialResponseSchema) GetCreatedDate() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedDate
}

func (a *APICredentialResponseSchema) GetLastUpdatedBy() string {
	if a == nil {
		return ""
	}
	return a.LastUpdatedBy
}

func (a *APICredentialResponseSchema) GetLastUpdatedDate() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.LastUpdatedDate
}
