// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type APICredentialCreateRequestDTO struct {
	// Human-readable name of the API Credential.
	Name string `json:"name"`
	// Brief description of the purpose and usage for the API Credential.
	Description string `json:"description"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled bool `json:"enabled"`
	// Role assignments for the API Credential.
	Roles APICredentialRolesSchema `json:"roles"`
	// CIDR range enforced as the IP allowlist for the API Credential.
	IPAllowlist []string `json:"ipAllowlist,omitzero"`
}

func (a APICredentialCreateRequestDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APICredentialCreateRequestDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APICredentialCreateRequestDTO) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APICredentialCreateRequestDTO) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APICredentialCreateRequestDTO) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *APICredentialCreateRequestDTO) GetRoles() APICredentialRolesSchema {
	if a == nil {
		return APICredentialRolesSchema{}
	}
	return a.Roles
}

func (a *APICredentialCreateRequestDTO) GetIPAllowlist() []string {
	if a == nil {
		return nil
	}
	return a.IPAllowlist
}
