// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialsListResponseDTO struct {
	// List of API Credentials.
	Items []APICredentialResponseSchema `json:"items"`
	// Total number of API Credentials listed in the response.
	Count int64 `json:"count"`
}

func (a *APICredentialsListResponseDTO) GetItems() []APICredentialResponseSchema {
	if a == nil {
		return []APICredentialResponseSchema{}
	}
	return a.Items
}

func (a *APICredentialsListResponseDTO) GetCount() int64 {
	if a == nil {
		return 0
	}
	return a.Count
}
