// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialsListResponseDTO struct {
	// List of API credentials
	Items []APICredentialSchema `json:"items"`
	// Total number of API credentials
	Count float64 `json:"count"`
}

func (a *APICredentialsListResponseDTO) GetItems() []APICredentialSchema {
	if a == nil {
		return []APICredentialSchema{}
	}
	return a.Items
}

func (a *APICredentialsListResponseDTO) GetCount() float64 {
	if a == nil {
		return 0.0
	}
	return a.Count
}
