// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialsListResponseDTO struct {
	// List of API Credentials.
	Items []APICredentialListItemSchema `json:"items"`
	// Total number of API Credentials listed in the response.
	Count float64 `json:"count"`
}

func (a *APICredentialsListResponseDTO) GetItems() []APICredentialListItemSchema {
	if a == nil {
		return []APICredentialListItemSchema{}
	}
	return a.Items
}

func (a *APICredentialsListResponseDTO) GetCount() float64 {
	if a == nil {
		return 0.0
	}
	return a.Count
}
