// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialUpdateRequestDTO struct {
	// Human-readable name of the API Credential.
	Name *string `json:"name,omitempty"`
	// Brief description of the purpose and usage for the API Credential.
	Description *string `json:"description,omitempty"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled *bool `json:"enabled,omitempty"`
	// Role assignments for the API Credential.
	Roles *APICredentialRolesSchema `json:"roles,omitempty"`
}

func (a *APICredentialUpdateRequestDTO) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *APICredentialUpdateRequestDTO) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *APICredentialUpdateRequestDTO) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *APICredentialUpdateRequestDTO) GetRoles() *APICredentialRolesSchema {
	if a == nil {
		return nil
	}
	return a.Roles
}
