// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type APICredentialUpdateRequestDTO struct {
	// Human-readable name of the API Credential.
	Name *string `json:"name,omitzero"`
	// Brief description of the purpose and usage for the API Credential.
	Description *string `json:"description,omitzero"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled *bool `json:"enabled,omitzero"`
	// Role assignments for the API Credential.
	Roles *APICredentialRolesSchema `json:"roles,omitzero"`
}

func (a APICredentialUpdateRequestDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APICredentialUpdateRequestDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APICredentialUpdateRequestDTO) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *APICredentialUpdateRequestDTO) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *APICredentialUpdateRequestDTO) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *APICredentialUpdateRequestDTO) GetRoles() *APICredentialRolesSchema {
	if a == nil {
		return nil
	}
	return a.Roles
}
