// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APICredentialCreateRequestDTO struct {
	// Human-readable name of the API Credential.
	Name string `json:"name"`
	// Brief description of the purpose and usage for the API Credential.
	Description string `json:"description"`
	// If <code>true</code>, the API Credential is enabled. Otherwise, <code>false</code>.
	Enabled bool `json:"enabled"`
	// Unique ID of the Workspace.
	WorkspaceID string `json:"workspaceId"`
	// Role assignments for the API Credential.
	Roles APICredentialRolesSchema `json:"roles"`
}

func (a *APICredentialCreateRequestDTO) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *APICredentialCreateRequestDTO) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APICredentialCreateRequestDTO) GetEnabled() bool {
	if a == nil {
		return false
	}
	return a.Enabled
}

func (a *APICredentialCreateRequestDTO) GetWorkspaceID() string {
	if a == nil {
		return ""
	}
	return a.WorkspaceID
}

func (a *APICredentialCreateRequestDTO) GetRoles() APICredentialRolesSchema {
	if a == nil {
		return APICredentialRolesSchema{}
	}
	return a.Roles
}
