// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BillingWindow string

const (
	BillingWindowMonthly BillingWindow = "monthly"
	BillingWindowDaily   BillingWindow = "daily"
)

func (e BillingWindow) ToPointer() *BillingWindow {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillingWindow) IsExact() bool {
	if e != nil {
		switch *e {
		case "monthly", "daily":
			return true
		}
	}
	return false
}
