// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ContractsUtilizationResponseDTO struct {
	// Contract utilization data, grouped by contract period.
	Contracts []ContractUtilizationSchema `json:"contracts"`
}

func (c *ContractsUtilizationResponseDTO) GetContracts() []ContractUtilizationSchema {
	if c == nil {
		return []ContractUtilizationSchema{}
	}
	return c.Contracts
}
