// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"time"
)

type ContractUtilizationSchema struct {
	// Contract start date in ISO 8601 format.
	ContractStartDate time.Time `json:"contractStartDate"`
	// Contract end date in ISO 8601 format. Present only when the contract is closed.
	ContractEndDate *time.Time `json:"contractEndDate,omitzero"`
	// Cumulative credit utilization entries for the contract.
	Items []CreditsUtilizationItemSchema `json:"items"`
}

func (c ContractUtilizationSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContractUtilizationSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContractUtilizationSchema) GetContractStartDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.ContractStartDate
}

func (c *ContractUtilizationSchema) GetContractEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.ContractEndDate
}

func (c *ContractUtilizationSchema) GetItems() []CreditsUtilizationItemSchema {
	if c == nil {
		return []CreditsUtilizationItemSchema{}
	}
	return c.Items
}
