// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreditGrantsResponseDTO struct {
	// Credit grants for the queried period.
	Items []CreditGrantSchema `json:"items"`
	// Total number of items in the response.
	Count float64 `json:"count"`
}

func (c *CreditGrantsResponseDTO) GetItems() []CreditGrantSchema {
	if c == nil {
		return []CreditGrantSchema{}
	}
	return c.Items
}

func (c *CreditGrantsResponseDTO) GetCount() float64 {
	if c == nil {
		return 0.0
	}
	return c.Count
}
