// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"time"
)

// Type of the credit grant.
type Type string

const (
	TypeRefund    Type = "Refund"
	TypeRollover  Type = "Rollover"
	TypePurchased Type = "Purchased"
)

func (e Type) ToPointer() *Type {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Type) IsExact() bool {
	if e != nil {
		switch *e {
		case "Refund", "Rollover", "Purchased":
			return true
		}
	}
	return false
}

type CreditGrantSchema struct {
	// Date the grant was issued, in ISO 8601 format.
	Date time.Time `json:"date"`
	// Number of credits acquired by the grant.
	CreditsAcquired float64 `json:"creditsAcquired"`
	// Type of the credit grant.
	Type Type `json:"type"`
}

func (c CreditGrantSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditGrantSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditGrantSchema) GetDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Date
}

func (c *CreditGrantSchema) GetCreditsAcquired() float64 {
	if c == nil {
		return 0.0
	}
	return c.CreditsAcquired
}

func (c *CreditGrantSchema) GetType() Type {
	if c == nil {
		return Type("")
	}
	return c.Type
}
