// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreditsTimeseriesResponseDTO struct {
	// Credit timeseries data points.
	Items []CreditsTimeseriesItemSchema `json:"items"`
	// Total number of items in the response.
	Count float64 `json:"count"`
}

func (c *CreditsTimeseriesResponseDTO) GetItems() []CreditsTimeseriesItemSchema {
	if c == nil {
		return []CreditsTimeseriesItemSchema{}
	}
	return c.Items
}

func (c *CreditsTimeseriesResponseDTO) GetCount() float64 {
	if c == nil {
		return 0.0
	}
	return c.Count
}
