// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"time"
)

type CreditsUtilizationItemSchema struct {
	// Date of the aggregation window in ISO 8601 format.
	Date time.Time `json:"date"`
	// Number of credits consumed in the aggregation window.
	Credits float64 `json:"credits"`
}

func (c CreditsUtilizationItemSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditsUtilizationItemSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditsUtilizationItemSchema) GetDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Date
}

func (c *CreditsUtilizationItemSchema) GetCredits() float64 {
	if c == nil {
		return 0.0
	}
	return c.Credits
}
