// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type CreditsStatsResponseDTO struct {
	// Total credits remaining across all contracts.
	TotalCreditsRemaining float64 `json:"totalCreditsRemaining"`
	// Total credits consumed across all contracts.
	TotalCreditsUsed float64 `json:"totalCreditsUsed"`
	// Total credits acquired across all contracts.
	TotalCreditsAcquired float64 `json:"totalCreditsAcquired"`
	// Contract periods ordered by contract start date in reverse chronological order (newest first).
	Contracts []CreditsStatsContractSchema `json:"contracts,omitzero"`
}

func (c CreditsStatsResponseDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditsStatsResponseDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditsStatsResponseDTO) GetTotalCreditsRemaining() float64 {
	if c == nil {
		return 0.0
	}
	return c.TotalCreditsRemaining
}

func (c *CreditsStatsResponseDTO) GetTotalCreditsUsed() float64 {
	if c == nil {
		return 0.0
	}
	return c.TotalCreditsUsed
}

func (c *CreditsStatsResponseDTO) GetTotalCreditsAcquired() float64 {
	if c == nil {
		return 0.0
	}
	return c.TotalCreditsAcquired
}

func (c *CreditsStatsResponseDTO) GetContracts() []CreditsStatsContractSchema {
	if c == nil {
		return nil
	}
	return c.Contracts
}
