// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreditsTimeseriesDimensionSchema struct {
	// Dimension label for the credit breakdown.
	Dimension string `json:"dimension"`
	// Number of credits attributed to the dimension.
	Credits float64 `json:"credits"`
}

func (c *CreditsTimeseriesDimensionSchema) GetDimension() string {
	if c == nil {
		return ""
	}
	return c.Dimension
}

func (c *CreditsTimeseriesDimensionSchema) GetCredits() float64 {
	if c == nil {
		return 0.0
	}
	return c.Credits
}
