// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
	"time"
)

type CreditsStatsContractSchema struct {
	// Contract start date in ISO 8601 format.
	StartDate time.Time `json:"startDate"`
	// Contract end date in ISO 8601 format. Present only when the contract is closed.
	EndDate *time.Time `json:"endDate,omitzero"`
}

func (c CreditsStatsContractSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreditsStatsContractSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreditsStatsContractSchema) GetStartDate() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.StartDate
}

func (c *CreditsStatsContractSchema) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}
