// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DefaultErrorDTO struct {
	// HTTP status code.
	StatusCode int64 `json:"statusCode"`
	// Human-readable error message.
	Message string `json:"message"`
}

func (d *DefaultErrorDTO) GetStatusCode() int64 {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DefaultErrorDTO) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}
