// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Product name
type Product string

const (
	ProductEdge   Product = "edge"
	ProductSearch Product = "search"
	ProductStream Product = "stream"
	ProductLake   Product = "lake"
)

func (e Product) ToPointer() *Product {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Product) IsExact() bool {
	if e != nil {
		switch *e {
		case "edge", "search", "stream", "lake":
			return true
		}
	}
	return false
}

// Role for the product
type Role string

const (
	RoleAdmin    Role = "admin"
	RoleEditor   Role = "editor"
	RoleReader   Role = "reader"
	RoleUser     Role = "user"
	RoleNoaccess Role = "noaccess"
)

func (e Role) ToPointer() *Role {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Role) IsExact() bool {
	if e != nil {
		switch *e {
		case "admin", "editor", "reader", "user", "noaccess":
			return true
		}
	}
	return false
}

type ProductRoleSchema struct {
	// Product name
	Product Product `json:"product"`
	// Role for the product
	Role Role `json:"role"`
}

func (p *ProductRoleSchema) GetProduct() Product {
	if p == nil {
		return Product("")
	}
	return p.Product
}

func (p *ProductRoleSchema) GetRole() Role {
	if p == nil {
		return Role("")
	}
	return p.Role
}
