// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type SchemeOauth2 struct {
	ClientID     string `security:"name=clientID,env=criblmgmtplane_client_id"`
	ClientSecret string `security:"name=clientSecret,env=criblmgmtplane_client_secret"`
	TokenURL     string `default:"https://login.cribl.cloud/oauth2/token"`
	Audience     string `security:"name=audience,env=criblmgmtplane_audience"`
}

func (s SchemeOauth2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemeOauth2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SchemeOauth2) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *SchemeOauth2) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *SchemeOauth2) GetTokenURL() string {
	if o == nil {
		return ""
	}
	return o.TokenURL
}

func (o *SchemeOauth2) GetAudience() string {
	if o == nil {
		return ""
	}
	return o.Audience
}
