// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type Security struct {
	ClientOauth *SchemeClientOauth `security:"scheme,type=oauth2,subtype=client_credentials"`
	BearerAuth  *string            `security:"scheme,type=http,subtype=bearer,name=Authorization,env=criblmgmtplane_bearer_auth"`
}

func (s Security) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Security) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Security) GetClientOauth() *SchemeClientOauth {
	if s == nil {
		return nil
	}
	return s.ClientOauth
}

func (s *Security) GetBearerAuth() *string {
	if s == nil {
		return nil
	}
	return s.BearerAuth
}
