// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkspacesListResponseDTO struct {
	// List of workspaces
	Items []WorkspaceSchema `json:"items"`
	// Total number of workspaces
	Count float64 `json:"count"`
}

func (o *WorkspacesListResponseDTO) GetItems() []WorkspaceSchema {
	if o == nil {
		return []WorkspaceSchema{}
	}
	return o.Items
}

func (o *WorkspacesListResponseDTO) GetCount() float64 {
	if o == nil {
		return 0.0
	}
	return o.Count
}
