// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

// Region - AWS region where the Workspace is deployed.
type Region string

const (
	RegionUsWest2      Region = "us-west-2"
	RegionUsEast1      Region = "us-east-1"
	RegionUsEast2      Region = "us-east-2"
	RegionEuCentral1   Region = "eu-central-1"
	RegionEuCentral2   Region = "eu-central-2"
	RegionEuWest2      Region = "eu-west-2"
	RegionApSoutheast1 Region = "ap-southeast-1"
	RegionApSoutheast2 Region = "ap-southeast-2"
	RegionCaCentral1   Region = "ca-central-1"
	RegionApNortheast1 Region = "ap-northeast-1"
	RegionSaEast1      Region = "sa-east-1"
	RegionEuWest1      Region = "eu-west-1"
	RegionEuWest3      Region = "eu-west-3"
)

func (e Region) ToPointer() *Region {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Region) IsExact() bool {
	if e != nil {
		switch *e {
		case "us-west-2", "us-east-1", "us-east-2", "eu-central-1", "eu-central-2", "eu-west-2", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "ap-northeast-1", "sa-east-1", "eu-west-1", "eu-west-3":
			return true
		}
	}
	return false
}

// State - Current state of the Workspace.
type State string

const (
	StateProvisioning   State = "Provisioning"
	StateActive         State = "Active"
	StateInactive       State = "Inactive"
	StateFailed         State = "Failed"
	StateDeprovisioning State = "Deprovisioning"
)

func (e State) ToPointer() *State {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *State) IsExact() bool {
	if e != nil {
		switch *e {
		case "Provisioning", "Active", "Inactive", "Failed", "Deprovisioning":
			return true
		}
	}
	return false
}

type WorkspaceSchema struct {
	// Unique identifier for the Workspace.
	WorkspaceID string `json:"workspaceId"`
	// AWS region where the Workspace is deployed.
	Region Region `json:"region"`
	// Fully Qualified Domain Name (FQDN) of the Workspace Leader.
	LeaderFQDN string `json:"leaderFQDN"`
	// Current state of the Workspace.
	State State `json:"state"`
	// User-friendly alias for the Workspace.
	Alias *string `json:"alias,omitzero"`
	// Brief description of the Workspace.
	Description *string `json:"description,omitzero"`
	// Tags associated with the Workspace.
	Tags []string `json:"tags,omitzero"`
}

func (w WorkspaceSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspaceSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspaceSchema) GetWorkspaceID() string {
	if w == nil {
		return ""
	}
	return w.WorkspaceID
}

func (w *WorkspaceSchema) GetRegion() Region {
	if w == nil {
		return Region("")
	}
	return w.Region
}

func (w *WorkspaceSchema) GetLeaderFQDN() string {
	if w == nil {
		return ""
	}
	return w.LeaderFQDN
}

func (w *WorkspaceSchema) GetState() State {
	if w == nil {
		return State("")
	}
	return w.State
}

func (w *WorkspaceSchema) GetAlias() *string {
	if w == nil {
		return nil
	}
	return w.Alias
}

func (w *WorkspaceSchema) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WorkspaceSchema) GetTags() []string {
	if w == nil {
		return nil
	}
	return w.Tags
}
