// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

// WorkspaceRole - Role assigned to the API Credential on the Workspace.
type WorkspaceRole string

const (
	WorkspaceRoleOwner    WorkspaceRole = "owner"
	WorkspaceRoleAdmin    WorkspaceRole = "admin"
	WorkspaceRoleUser     WorkspaceRole = "user"
	WorkspaceRoleNoaccess WorkspaceRole = "noaccess"
)

func (e WorkspaceRole) ToPointer() *WorkspaceRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorkspaceRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "owner", "admin", "user", "noaccess":
			return true
		}
	}
	return false
}

type WorkspaceRoleSchema struct {
	// Unique ID of the Workspace.
	WorkspaceID string `json:"workspaceId"`
	// Role assigned to the API Credential on the Workspace.
	WorkspaceRole WorkspaceRole `json:"workspaceRole"`
	// Product-level Roles assigned to the API Credential for the Workspace.
	Products []ProductRoleSchema `json:"products,omitzero"`
}

func (w WorkspaceRoleSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspaceRoleSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspaceRoleSchema) GetWorkspaceID() string {
	if w == nil {
		return ""
	}
	return w.WorkspaceID
}

func (w *WorkspaceRoleSchema) GetWorkspaceRole() WorkspaceRole {
	if w == nil {
		return WorkspaceRole("")
	}
	return w.WorkspaceRole
}

func (w *WorkspaceRoleSchema) GetProducts() []ProductRoleSchema {
	if w == nil {
		return nil
	}
	return w.Products
}
