// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WorkspaceRole - Role in the workspace
type WorkspaceRole string

const (
	WorkspaceRoleOwner    WorkspaceRole = "owner"
	WorkspaceRoleAdmin    WorkspaceRole = "admin"
	WorkspaceRoleUser     WorkspaceRole = "user"
	WorkspaceRoleNoaccess WorkspaceRole = "noaccess"
)

func (e WorkspaceRole) ToPointer() *WorkspaceRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WorkspaceRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "owner", "admin", "user", "noaccess":
			return true
		}
	}
	return false
}

type WorkspaceRoleSchema struct {
	// Workspace identifier
	WorkspaceID string `json:"workspaceId"`
	// Role in the workspace
	WorkspaceRole WorkspaceRole `json:"workspaceRole"`
	// Product roles in the workspace
	Products []ProductRoleSchema `json:"products,omitempty"`
}

func (w *WorkspaceRoleSchema) GetWorkspaceID() string {
	if w == nil {
		return ""
	}
	return w.WorkspaceID
}

func (w *WorkspaceRoleSchema) GetWorkspaceRole() WorkspaceRole {
	if w == nil {
		return WorkspaceRole("")
	}
	return w.WorkspaceRole
}

func (w *WorkspaceRoleSchema) GetProducts() []ProductRoleSchema {
	if w == nil {
		return nil
	}
	return w.Products
}
