// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type WorkspaceCreateRequestDTO struct {
	// Unique identifier for the workspace
	WorkspaceID string `json:"workspaceId"`
	// User-friendly alias for the workspace
	Alias *string `json:"alias,omitzero"`
	// Detailed description of the workspace
	Description *string `json:"description,omitzero"`
	// Tags associated with the workspace
	Tags []string `json:"tags,omitzero"`
}

func (w WorkspaceCreateRequestDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspaceCreateRequestDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspaceCreateRequestDTO) GetWorkspaceID() string {
	if w == nil {
		return ""
	}
	return w.WorkspaceID
}

func (w *WorkspaceCreateRequestDTO) GetAlias() *string {
	if w == nil {
		return nil
	}
	return w.Alias
}

func (w *WorkspaceCreateRequestDTO) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WorkspaceCreateRequestDTO) GetTags() []string {
	if w == nil {
		return nil
	}
	return w.Tags
}
