// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkspacesListResponseDTO struct {
	// List of workspaces
	Items []WorkspaceSchema `json:"items"`
	// Total number of workspaces
	Count int64 `json:"count"`
}

func (w *WorkspacesListResponseDTO) GetItems() []WorkspaceSchema {
	if w == nil {
		return []WorkspaceSchema{}
	}
	return w.Items
}

func (w *WorkspacesListResponseDTO) GetCount() int64 {
	if w == nil {
		return 0
	}
	return w.Count
}
