// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/criblio/cribl-cloud-management-sdk-go/internal/utils"
)

type WorkspacePatchRequestDTO struct {
	// User-friendly alias for the Workspace.
	Alias *string `json:"alias,omitzero"`
	// Brief description of the Workspace.
	Description *string `json:"description,omitzero"`
	// Tags associated with the Workspace.
	Tags []string `json:"tags,omitzero"`
}

func (w WorkspacePatchRequestDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspacePatchRequestDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WorkspacePatchRequestDTO) GetAlias() *string {
	if w == nil {
		return nil
	}
	return w.Alias
}

func (w *WorkspacePatchRequestDTO) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WorkspacePatchRequestDTO) GetTags() []string {
	if w == nil {
		return nil
	}
	return w.Tags
}
