// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WorkspaceCreateRequestDTORegion - AWS region where the workspace is deployed
type WorkspaceCreateRequestDTORegion string

const (
	WorkspaceCreateRequestDTORegionUsWest2      WorkspaceCreateRequestDTORegion = "us-west-2"
	WorkspaceCreateRequestDTORegionUsEast1      WorkspaceCreateRequestDTORegion = "us-east-1"
	WorkspaceCreateRequestDTORegionEuCentral1   WorkspaceCreateRequestDTORegion = "eu-central-1"
	WorkspaceCreateRequestDTORegionEuWest2      WorkspaceCreateRequestDTORegion = "eu-west-2"
	WorkspaceCreateRequestDTORegionApSoutheast2 WorkspaceCreateRequestDTORegion = "ap-southeast-2"
	WorkspaceCreateRequestDTORegionCaCentral1   WorkspaceCreateRequestDTORegion = "ca-central-1"
	WorkspaceCreateRequestDTORegionUsEast2      WorkspaceCreateRequestDTORegion = "us-east-2"
)

func (e WorkspaceCreateRequestDTORegion) ToPointer() *WorkspaceCreateRequestDTORegion {
	return &e
}

type WorkspaceCreateRequestDTO struct {
	// Unique identifier for the workspace
	WorkspaceID string `json:"workspaceId"`
	// AWS region where the workspace is deployed
	Region WorkspaceCreateRequestDTORegion `json:"region"`
	// User-friendly alias for the workspace
	Alias *string `json:"alias,omitempty"`
	// Detailed description of the workspace
	Description *string `json:"description,omitempty"`
	// Tags associated with the workspace
	Tags []string `json:"tags,omitempty"`
}

func (w *WorkspaceCreateRequestDTO) GetWorkspaceID() string {
	if w == nil {
		return ""
	}
	return w.WorkspaceID
}

func (w *WorkspaceCreateRequestDTO) GetRegion() WorkspaceCreateRequestDTORegion {
	if w == nil {
		return WorkspaceCreateRequestDTORegion("")
	}
	return w.Region
}

func (w *WorkspaceCreateRequestDTO) GetAlias() *string {
	if w == nil {
		return nil
	}
	return w.Alias
}

func (w *WorkspaceCreateRequestDTO) GetDescription() *string {
	if w == nil {
		return nil
	}
	return w.Description
}

func (w *WorkspaceCreateRequestDTO) GetTags() []string {
	if w == nil {
		return nil
	}
	return w.Tags
}
