// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/criblio/cribl-cloud-management-sdk-go/models/components"
)

type DefaultErrorDTO struct {
	// HTTP status code.
	StatusCode int64 `json:"statusCode"`
	// Human-readable error message.
	Message  string                  `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DefaultErrorDTO{}

func (e *DefaultErrorDTO) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
