workflowVersion: 1.0.0
speakeasyVersion: 1.674.0
sources:
    Cribl Cloud Management API:
        inputs:
            - location: ./openapi.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-cloud-management-api
targets:
    cribl-mgmt-plane:
        target: go
        source: Cribl Cloud Management API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/cribl/cribl/cribl-cloud-management-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
        testing:
            enabled: false
